# training_data.py
training_data = [
    ["THIS ASSIGNMENT OF RENTS dated March 21 2023 is made and executed between Ashton Gaskins Storage LLC whose address is 1 Hallshire CT Dallas TX 75225 A Texas Limited Liability Company referred to below as Grantor and Legacy Bank whose address is 3696 N HWY 81 Duncan OK 73533 1294 referred to below as Lender ASSIGNMENT For valuable consideration Grantor hereby assigns grants a continuing security interest in and conveys to Lender all of Grantor s right title and interest in and to the Rents from the following described Property located in Collin County State of Texas ",{"entities":[[74,100,"GRANTOR"],[149,182,"GRANTOR"],[216,227,"GRANTEE"]]}],
["THIS SPECIAL WARRANTY DEED this Deed is made as of 2023 by HINES MILRANY RANCH LLC a Delaware limited liability company Grantor to K HOVNANIAN DFW MILRANY RANCH LLC a Texas limited liability company whose address is 5808 W Plano Parkway Plano Texas 75093 4636 Grantee ",{"entities":[[59,119,"GRANTOR"],[131,164,"GRANTEE"]]}],
["Notice of conﬁdentiality ifyou are a natural person you may remove or strike any or all of the followinginlomiationfrom anyinstrnrnentthattransfersan interestinrealpropertylieioreit isﬁled for record in the public records your social security number or your drivers license number Date March 17 2023 Property Owner Mark Fanning IBOIIO Midway Rd APT 196 Dallas TX 75287 Transferee Home Tax Solutions LLC ",{"entities":[[315,327,"GRANTOR"],[380,402,"GRANTEE"]]}],
[" THIS SPECIAL WARRANTY DEED this Deed is made as of _ 2023 by HINES MILRANY RANCH LLC a Delaware limited liability company Grantor to K HOVNANIAN DFW MILRANY RANCH LLC a Texas limited liability company whose address is 5808 W Plano Parkway Plano Texas 75093 4636 Grantee For and in consideration of the sum of Ten and No 100 Dollars and other valuable consideration to Grantor paid by the Grantee the receipt and sufﬁciency ",{"entities":[[62,122,"GRANTOR"],[134,201,"GRANTEE"]]}],
["THIS SPECIAL WARRANTY DEED this Deed is made as of Marchig 2023 by HINES MILRANY RANCH LLC a Delaware limited liability company Grantor to K HOVNANIAN DF W MILRANY RANCH LLC a Texas limited liability company whose address is 5808 W Plano Parkway Plano Texas 75093 4636 Grantee For and in consideration of the sum of Ten and No 100 Dollars and other valuable consideration to Grantor paid by the Grantee the receipt and sufficiency of which are ",{"entities":[[67,127,"GRANTOR"],[139,207,"GRANTEE"]]}],
[" A Security Instrument means this document which is dated March 11 2023 together will all Riders to this document B Borrower and grantor of this Security Instrument is CHRISTOPHER R CUNNINGHAM NICOLE S CUNNINGHAM C Lender is Bank of America NA National Banking Association Lender s address is 100 North Tryon St reet Charlotte North Carolina 28255 Lender includes any holder of the Note and any successor or assign who is entitled to receive payments under the ",{"entities":[[168,212,"GRANTOR"],[225,272,"GRANTEE"]]}],
[" Before me the undersigned authority a Notary Public in and for the State of Texas on this day personally appeared CHRISTOPHER R CUNNINGHAM NICOLE S CUNNINGHAM and on oath such individual or each of them swears that the following statements are true I understand that the lender making the Extension of Credit is Bank of America NA the Lender ",{"entities":[[115,139,"GRANTOR"],[140,159,"GRANTOR"],[313,331,"GRANTEE"]]}],
[" For Value Received the present undersigned Beneﬁciary under a deed of trust executed by JOHN ZEILAN AND YVONNE ZEILAN HUSBAND AND WIFE to SCOTT EVERETT as Trustee dated 05 12 2014 certiﬁes that the Deed of Trust has been fully paid satisﬁed or otherwise discharged The Deed of Trust was recorded in the Deed of Trust Records of Collin County Texas on 05 13 2014 and is indexed as Volume 1 I _A _Page Iﬂjile No Original Beneﬁciary MORTGAGE ELECTRONIC REGISTRATION SYSTEMS INC AS BENEFICIARY AS ",{"entities":[[89,100,"GRANTOR"],[105,118,"GRANTOR"],[431,475,"GRANTEE"]]}],
[" THIS SPECIAL WARRANTY DEED this Deed is made as of Marchag 2023 by HINES MILRANY RANCH LLC a Delaware limited liability company Grantor to K HOVNANIAN DFW MILRANY RANCH LLC a Texas limited liability company whose address is 5808 W Plano Parkway Plano Texas 75093 4636 Grantee For and in consideration of the sum of Ten and No 100 Dollars and other valuable ",{"entities":[[68,128,"GRANTOR"],[140,207,"GRANTEE"]]}],
["Said Deed of Trust or Mortgage dated NOVEMBER 06 2020 and executed by PETER JAMES SANCHEZ AND CHRISTINE ELIZABETH SANCHEZ HUSBAND AND WIFE Trustor or Grantor Whose mailing address is 2105 LEEDS DR PLANO TX 750253141 Trustor or Grantor to ANDREA K MAGERS Trustee for the beneﬁt of MORTGAGE ELECTRONIC REGISTRATION SYSTEMS INC MERS AS BENEFICIARY AS NOMINEE FOR QUICKEN LOANS LLC ITS SUCCESSORS AND ASSIGNS Original Beneﬁciary or Grantee ",{"entities":[[70,89,"GRANTOR"],[94,121,"GRANTOR"],[238,253,"GRANTEE"]]}],
["The LIEN CLAIM or MECI ANIC S LIEN by Moore Supply Co GM against WPC i I 1560 NORTH HARDJN BOULEVARD STORAGE LLC WENTWORTH STORAGE ACQUISITIONS LLC 802 N 3RD AVE PHOENIX AZ 85003 upon the foilowing real property located in the City of MCKINNEY in the County of Coilin in the State of Texas has been paid in full contract information is for Our Jobllnvoice 1510649 The name of the person to whom claimant furnished the labor services equipment or materials to was PARAMOUNT PLUMBING 7415 WHITEHALL ST STE 109 RICHLAND HELLS TX 76118 ",{"entities":[[78,147,"GRANTOR"],[463,481,"GRANTEE"]]}],
[" A Borrower is Kesava Naidu Kakarla and Jyothi Chava Husband and Wife currently residing at 2101 Adleigh Rd Celina TX 75009 US Borrower is the grantor under this Security Instrument B Lender is Digital Federal Credit Union Lender is a Federal Credit Union organized and existing under the laws of MA Lender s address is 853 Donald Lynch Blvd Marlborough MA 01752 Lender is the beneﬁciary under this Security Instrument The term Lender includes any successors and assigns of Lender ",{"entities":[[15,35,"GRANTOR"],[40,52,"GRANTOR"],[194,222,"GRANTEE"]]}],
[" NOTICE OF CONFIDENTIALITY RIGHTS IF YOU ARE A NATURAL PERSON YOU MAY REMOVE OR STRIKE ANY OR ALL OF THE FOLLOWING INFORMATION FROM ANY INSTRUMENT THAT TRANSFERS AN INTEREST IN REAL PROPERTY BEFORE IT IS FILED FOR RECORD IN THE PUBLIC RECORDS YOUR SOCIAL SECURITY NUMBER OR YOUR DRIVER S LICENSE NUMBER DEED OF TRUST Assignment of Leases and Financing Statement Date March 17 2023 Grantor Bluehaven Homes Lakepointe LLC a Texas limited liability company Grantor s Mailing Address 5701 Time Square Blvd 200 Amarillo TX 79119 Trustee Darrell G Adams Trustee s Mailing Address 6565 Hillcrest Avenue Suite 400 Dallas TX 75205 Lender PLAIN SCAPITAL BANK Lender s Mailing Address 18111 Preston Road Ste 110 Dallas Texas 75252 ",{"entities":[[389,453,"GRANTOR"],[629,648,"GRANTEE"]]}],
["GENERAL WARRANTY DEED WITH VENDOR S LIEN Grantor Joseph E Hehnberger and Debra S Helmberger husband and wife Grantee Manuel Nevarez Carbajal a single man Consideration Ten and No 100 Dollars 10 00 and other good and valuable consideration the receipt and sufﬁciency of which is hereby acknowledged by Grantor and the further consideration of a promissory note in the amount of Fifty Thousand Two Hundred and 00 100 Dollars 50 000 00 payable to the order ",{"entities":[[49,68,"GRANTOR"],[73,91,"GRANTOR"],[117,140,"GRANTEE"]]}],
[" Property including any improvements Lot 7 Block 2 Woodard Addition Lots 4R 5 8 Block 2 an Addition to the City of F armersville Collin County Texas according to the map or plat Deed of Trust Terms March Q 2023 Manuel Nevarez Carbajal 3340 Melody Lane Princeton Texas 75407 Kerry L Prisock 1371 Hayward Drive Rockwall Rockwall County Texas 75087 Joseph E Helmberger and Debra S Helmberger 315 Houston Street Farmersville Texas 75442",{"entities":[[211,234,"GRANTOR"],[346,365,"GRANTEE"],[370,388,"GRANTEE"]]}],
["Borrower Bluehaven Homes Lakepointe LLC a Texas limited liability company Lender PLAINSCAPITAL BANK Maturity date March 17 2024 Property including any improvements Lot 14 Block L of LAKEPOINTE PHASE IIB an Addition to the City of Lavon Collin County Texas according to the Map or Plat thereof recorded in Volume 2021 Page 700 of the Plat Records of Collin County Texas together with all rights privileges and appurtenances pertaining thereto and improvements located thereon including ",{"entities":[[9,73,"GRANTOR"],[81,99,"GRANTEE"]]}],
["COUNTY OF COLLIN I Patrick J Schurr attorney for Judgment Plaintiff STEPHEN A RAPP certify that in cause no CV 21 1621 in the 397TH Judicial District for Grayson County Texas the Lawsuit Judgment Plaintiff recovered a default judgment against Judgment Defendants TEXOMA AUTO REMARKETING LLC DUSTIN FORD and MFDF TRANSPORTATION LLC the Judgment Defendants ",{"entities":[[19,35,"GRANTOR"],[263,302,"GRANTEE"],[307,330,"GRANTEE"]]}],
[" 1 Name and Address of Owner hereinafter the Owner WILLIAM F MCINERNEY 513 BRIDLE COURT4 Beneﬁciary Effective upon the death of the Owner the Owner grants and conveys the Property to MICHAEL J MCINERNEY who resides at 880 CREEKWOOD CIRCLE FAIRVIEW TX 75069 the Grantee to have and hold the Property forever FAIRVIEW TEXAS 75069 ",{"entities":[[51,70,"GRANTOR"],[183,202,"GRANTEE"]]}],

]

def convert_to_mitie_format(sentence, entities):
    mitie_tokens = []
    for entity_start, entity_end, entity_type in entities:
        entity_text = sentence[entity_start:entity_end]
        mitie_tokens.append(f"{entity_text}:{entity_type}")
    return ' '.join(mitie_tokens)

# Convert and write to MITIE training file
mitie_training_data = []
for sentence, entities in training_data:
    mitie_line = convert_to_mitie_format(sentence, entities['entities'])
    mitie_training_data.append(mitie_line)

# Write to a MITIE training file
with open("mitie_training_data.txt", "w") as f:
    for line in mitie_training_data:
        f.write(line + '\n')
